### ISSUE TITLE
关于视频打开异常问题

### ISSUE THREAD

**Issue by pygogogo** [YaoFANGUK/video-subtitle-extractor#10]
作者你好！我用了你的项目，感觉准确率特别高，几乎没有什么错误，在这里非常感谢你的分享，但是我今天在使用的时候遇到了一个问题，困惑了我很久，就是我下载的视频，用你的可视化界面打开的时候，是打不开的，但是当我先打开一个其他可用视频，然后再打开我之前那个打不开的视频的时候，我就可以看到这个视频的画面了（这个问题视频我用某些播放器可以打开，某些播放器只能听到音频），请问一下这是什么原因，因为我找不到这个视频的其他资源了，所以想像你请教一下

**Comment by pygogogo** [comment]
![bd4b94537af828577d80c4145ae217f](https://user-images.githubusercontent.com/45659426/119459849-a6f51b00-bd70-11eb-89e6-2dff09f8ab95.png)
上面这张是我打开其他可用视频，下面这张是我再去打开之前那个不可用的视频，就可以看见了，但是如果点运行的话，无法正常运行
![696185c37d295899916f954152e086d](https://user-images.githubusercontent.com/45659426/119460034-d6a42300-bd70-11eb-8be3-7649a9cd8583.png)

**Comment by YaoFANGUK** [comment]
这个软件底层用的opencv打开的视频，如果视频本身有问题的话是打不开，你可以尝试将问题视频转码成大部分播放器可以播放的视频格式（最好mp4 x264编码），然后再进行提取

**Comment by YaoFANGUK** [comment]
你也可以把问题视频发我邮箱 flavioy@live.com 我帮你看看

**Comment by pygogogo** [comment]
我通过将视频转码成你说的格式以后，问题已经解决了，非常感谢！
