### ISSUE TITLE
时间轴不准确

### ISSUE THREAD

**Issue by Marvll** [YaoFANGUK/video-subtitle-extractor#118]
![image](https://user-images.githubusercontent.com/88202244/166987416-447280ca-29e6-44e6-961e-73793fca7341.png)
OCR对比源

**Comment by YaoFANGUK** [comment]
什么平台运行的，什么模式，windows快速还是精准，还是macos，还是linux

**Comment by Marvll** [comment]
> 什么平台运行的，什么模式，windows快速还是精准，还是macos，还是linux

Windows 11 ，快速模式
![image](https://user-images.githubusercontent.com/88202244/167060516-9b1d6156-375e-4510-ba3f-6b85431ea6c7.png)

**Comment by YaoFANGUK** [comment]
换精准模式试试

**Comment by Marvll** [comment]
`字幕区域：(677,727,576,1344)
Running Verify Fluid Program ... 
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
识别字幕语言：ch
识别模式：accurate
使用GPU进行加速
帧数：183682.0，帧率：24.0
【处理中】开启提取视频关键帧...
字幕帧：59, 耗时: 0.12511348724365234
字幕帧：60, 耗时: 0.13011860847473145
字幕帧：61, 耗时: 0.131119966506958
字幕帧：62, 耗时: 0.1311202049255371
字幕帧：63, 耗时: 0.13092494010925293
字幕帧：64, 耗时: 0.1339576244354248
字幕帧：65, 耗时: 0.13098835945129395
字幕帧：66, 耗时: 0.1311197280883789
字幕帧：67, 耗时: 0.12811660766601562
字幕帧：68, 耗时: 0.12911772727966309
字幕帧：69, 耗时: 0.1361234188079834
字幕帧：70, 耗时: 0.13212108612060547
字幕帧：71, 耗时: 0.12897706031799316
字幕帧：72, 耗时: 0.12911748886108398
字幕帧：73, 耗时: 0.1307077407836914
字幕帧：74, 耗时: 0.1311192512512207
字幕帧：75, 耗时: 0.1325690746307373
字幕帧：76, 耗时: 0.14613747596740723
字幕帧：77, 耗时: 0.13712477684020996
字幕帧：78, 耗时: 0.1361243724822998
字幕帧：79, 耗时: 0.13712406158447266
字幕帧：80, 耗时: 0.13712525367736816
字幕帧：81, 耗时: 0.134049654006958
字幕帧：82, 耗时: 0.1369032859802246
字幕帧：83, 耗时: 0.13011693954467773
字幕帧：84, 耗时: 0.12971735000610352
字幕帧：85, 耗时: 0.12986540794372559
字幕帧：86, 耗时: 0.1299269199371338
字幕帧：87, 耗时: 0.12902402877807617
字幕帧：88, 耗时: 0.13312673568725586
字幕帧：89, 耗时: 0.12711572647094727
字幕帧：90, 耗时: 0.13011765480041504
字幕帧：91, 耗时: 0.12998175621032715
字幕帧：92, 耗时: 0.1309185028076172
字幕帧：93, 耗时: 0.13491106033325195
字幕帧：94, 耗时: 0.13011765480041504
字幕帧：95, 耗时: 0.12811660766601562
字幕帧：96, 耗时: 0.12911581993103027
字幕帧：97, 耗时: 0.12811708450317383
字幕帧：98, 耗时: 0.12966370582580566
字幕帧：99, 耗时: 0.13012218475341797
字幕帧：100, 耗时: 0.1299729347229004
字幕帧：101, 耗时: 0.126115083694458
字幕帧：102, 耗时: 0.13011837005615234
字幕帧：103, 耗时: 0.13011813163757324
字幕帧：104, 耗时: 0.12911772727966309
字幕帧：105, 耗时: 0.12811660766601562
字幕帧：106, 耗时: 0.12911748886108398
字幕帧：107, 耗时: 0.13065242767333984
字幕帧：108, 耗时: 0.13211917877197266
字幕帧：109, 耗时: 0.12912249565124512
字幕帧：110, 耗时: 0.13232851028442383
字幕帧：111, 耗时: 0.12711405754089355
字幕帧：112, 耗时: 0.13011860847473145
字幕帧：113, 耗时: 0.1311185359954834
字幕帧：114, 耗时: 0.13011789321899414
字幕帧：115, 耗时: 0.12711524963378906
字幕帧：116, 耗时: 0.12811636924743652
字幕帧：117, 耗时: 0.13080859184265137
字幕帧：118, 耗时: 0.13011813163757324
字幕帧：119, 耗时: 0.12900471687316895
字幕帧：120, 耗时: 0.1311192512512207
字幕帧：121, 耗时: 0.13312149047851562
字幕帧：122, 耗时: 0.13212013244628906
字幕帧：123, 耗时: 0.12711548805236816
字幕帧：124, 耗时: 0.13211965560913086
字幕帧：125, 耗时: 0.1311187744140625
字幕帧：126, 耗时: 0.1411271095275879
字幕帧：127, 耗时: 0.13412141799926758
字幕帧：128, 耗时: 0.12760663032531738
字幕帧：129, 耗时: 0.13412165641784668
字幕帧：130, 耗时: 0.13011837005615234
字幕帧：131, 耗时: 0.12914800643920898
字幕帧：132, 耗时: 0.12811636924743652
字幕帧：133, 耗时: 0.13279008865356445
字幕帧：134, 耗时: 0.13312029838562012
字幕帧：135, 耗时: 0.13191676139831543
字幕帧：136, 耗时: 0.13512253761291504
字幕帧：137, 耗时: 0.1350541114807129
字幕帧：138, 耗时: 0.12811613082885742
字幕帧：139, 耗时: 0.13115382194519043
字幕帧：140, 耗时: 0.13311982154846191
字幕帧：141, 耗时: 0.12811493873596191
字幕帧：142, 耗时: 0.13212037086486816
字幕帧：143, 耗时: 0.16199040412902832
字幕帧：144, 耗时: 0.12411260604858398
字幕帧：145, 耗时: 0.13211965560913086
字幕帧：146, 耗时: 0.1311197280883789
字幕帧：147, 耗时: 0.12711596488952637
字幕帧：148, 耗时: 0.13412141799926758
字幕帧：149, 耗时: 0.13212013244628906
字幕帧：150, 耗时: 0.13011837005615234
字幕帧：324, 耗时: 0.12365841865539551
字幕帧：326, 耗时: 0.12511372566223145
字幕帧：329, 耗时: 0.12511396408081055
字幕帧：330, 耗时: 0.12711596488952637
字幕帧：336, 耗时: 0.1261141300201416
字幕帧：338, 耗时: 0.12411284446716309
字幕帧：339, 耗时: 0.12784147262573242
字幕帧：420, 耗时: 0.12359118461608887
字幕帧：427, 耗时: 0.12311148643493652
字幕帧：428, 耗时: 0.12511372566223145
字幕帧：429, 耗时: 0.1277627944946289
字幕帧：430, 耗时: 0.12811589241027832
字幕帧：431, 耗时: 0.1260216236114502
字幕帧：432, 耗时: 0.12811565399169922
字幕帧：433, 耗时: 0.12711691856384277
字幕帧：434, 耗时: 0.12511396408081055
字幕帧：435, 耗时: 0.13718891143798828
字幕帧：436, 耗时: 0.13018512725830078
字幕帧：437, 耗时: 0.12811565399169922
字幕帧：438, 耗时: 0.12411308288574219
字幕帧：439, 耗时: 0.1261138916015625
字幕帧：440, 耗时: 0.12511372566223145
字幕帧：441, 耗时: 0.1293473243713379
字幕帧：442, 耗时: 0.12711477279663086
字幕帧：443, 耗时: 0.1259298324584961
字幕帧：486, 耗时: 0.10509538650512695`
卡住不动了

**Comment by YaoFANGUK** [comment]
大哥 你用的都是N 久前的版本了 麻烦用最新的
