### ISSUE TITLE
srt是空文件，然后手动安装GPU版本始终无法安装最后一步

### ISSUE THREAD

**Issue by gazygaygay** [YaoFANGUK/video-subtitle-extractor#119]
pip install -r requirements_gpu.txt 这一行无法安装，显示找不到，其他每一步都没问题。影片获取关键帧后秒输出srt，但是都是空文件。希望得到帮助

**Comment by YaoFANGUK** [comment]
找不到说明你没cd到这个文件在的路径，这个要是不知道的话建议用cpu版本

**Comment by gazygaygay** [comment]
感谢作者解答，目前已经解决问题，发现重启即可，看到群内还有其他老哥也是这样，作者看看要不要步骤中写一下重启再使用。非常感谢作者的项目，解决燃眉之急
