### ISSUE TITLE
运行图形版本程序后看不到“”运行“”按钮

### ISSUE THREAD

**Issue by tkfanswind** [YaoFANGUK/video-subtitle-extractor#12]
运行图形版本程序后看不到“”运行“”按钮。
窗口不能拖拽放大缩小，也不能最大化。完全没有 “运行”按钮

**Comment by YaoFANGUK** [comment]
请问下电脑分辨率是多少呢 另外什么操作系统呢

**Comment by tkfanswind** [comment]
1366x768  Windows 7 64位

我尝试改过分辨率始终看不到运行按钮。也不能拖拽窗口，调节窗口大小。我用的CPU那个绿色版本

**Comment by YaoFANGUK** [comment]
系统有点旧了呢 我是在win10构建的 建议你使用win10 1920*1080p以上的机器运行

**Comment by WangJunliang123** [comment]
你可以尝试将src/GUI.py中布局函数的109、110行代码剪切到82行之后。可以出现运行按钮。

**Comment by yeunggor** [comment]
1280X768 也一樣情況..... 希望有辦法解決

**Comment by YaoFANGUK** [comment]
bug已经修复 请使用最新的代码
