### ISSUE TITLE
Windows下文件大小写不敏感

### ISSUE THREAD

**Issue by Marvll** [YaoFANGUK/video-subtitle-extractor#124]
`backend/ppocr/utils/dict/EN_dict.txt`
`backend/ppocr/utils/dict/en_dict.txt`

**Comment by YaoFANGUK** [comment]
那只能怪Windows辣鸡啊

**Comment by YaoFANGUK** [comment]
已经删了EN_dict.txt了

**Comment by eritpchy** [comment]
放心，市面上的系统就没有不拉几的
