### ISSUE TITLE
最近突然开始时间轴混乱了

### ISSUE THREAD

**Issue by zcl92** [YaoFANGUK/video-subtitle-extractor#128]
首先我要感谢开发者开发的这款软件，它让我在制作字幕时方便了很多。

大约一个月前，我第一次用vse.exe那个版本时，成功提取了两个一小时节目的英文字幕，无论字幕还是时间轴都完全正确。但是在那之后，再提取字幕时，就会出现字幕出现过早的情况。。假设视频中出现了第1句硬字幕、第2句硬字幕和第3句硬字幕，则提取后，第2句的字幕出现在第3句的时间轴，第3句的字幕出现在第4句的时间轴上。且由于提取后的字幕和原视频字幕在时间轴上差的时间间隔不一样，导致无法整体平移时间轴来对上原视频的字幕时间轴。想问一下有解决方法吗？谢谢

祝愿开发人员工作顺利，身体健康

**Comment by YaoFANGUK** [comment]
视频发下 具体的运行环境说下 windows还是mac还是Linux 运行的gpu还是cpu 运行的精准还是快速 什么都不说我排查不到原因

**Comment by xwlcn** [comment]
确实是这样，新版本有问题。

**Comment by hakolove** [comment]
我也出现了一样的问题。用来给电视剧视频做轴的时候，指不定从中间某一句开始，轴和文字就对不上了，这一句的文字的时间轴是下一句字幕的~之前的版本我没用过，不知道是不是新版本的问题~ 还是很感谢开发者！

**Comment by YaoFANGUK** [comment]
最新的源码已经修复该问题
