### ISSUE TITLE
vse virus report

### ISSUE THREAD

**Issue by shawkynasr** [YaoFANGUK/video-subtitle-extractor#136]
Downloading vse.exe

Python/Packed.Nuitka.F 可疑应用程序 的变量

Using ESET Internet Security

﻿时间;扫描程序;对象类型;对象;检测;操作;用户;信息;哈希;此处首次所见
2022/6/21 15:09:00;文件系统实时防护;文件;C:\Users\**\Downloads\vse.mdG0H1Dp.exe.part;Python/Packed.Nuitka.F 可疑应用程序 的变量;已通过删除清除;DESKTOP-5FU7PIQ\**;在通过应用程序修改的文件上发生了事件: C:\Program Files\Mozilla Firefox\firefox.exe (D9AA8FB6A2F331FF3B7983539E8B3BF138A7C45B).;1FF40E2D8E8007191151990965AA90ABEEED9CF4;2022/6/21 15:04:57

**Comment by YaoFANGUK** [comment]
哪里下载的程序

**Comment by shawkynasr** [comment]
Windows 单文件版本(双击直接运行，每次打开时会有一点慢，推荐小白使用)： [vse.exe](https://github.91chi.fun/https://github.com//YaoFANGUK/video-subtitle-extractor/releases/download/1.0.0/vse.exe)

**Comment by YaoFANGUK** [comment]
担心打包的程序有问题建议查阅源码后运行源码

**Comment by shawkynasr** [comment]
vse_windows_CPU.zip下载了，正常的。
