### ISSUE TITLE
字幕时间轴错位

### ISSUE THREAD

**Issue by urna** [YaoFANGUK/video-subtitle-extractor#137]
今天下载的 [vse_windows_CPU.zip](https://github.91chi.fun/https://github.com//YaoFANGUK/video-subtitle-extractor/releases/download/1.0.0/vse_windows_CPU.zip)

提取倚天屠龙记～魔教教主电影字幕，从5分钟后字幕时间轴就错乱了，相关视频/字幕/log等在这里，供分析。用的是gui程序，快速模式。

链接: https://pan.baidu.com/s/1w2nXuc3GgqQzIrJUyNeHlA?pwd=82qh 提取码: 82qh

**Comment by urna** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data

**Comment by urna** [comment]
补充下，用春节前下载的版本又提取了下，老版本时间轴是正确的，但字幕内容略有差别，似乎新版本的字幕准确率提高了

**Comment by YaoFANGUK** [comment]
最近的源码已经修复

**Comment by urna** [comment]
确认修复

**Comment by helloxuejuxi** [comment]
> 确认修复

你试试精确模式，时间轴问题没解决

**Comment by YaoFANGUK** [comment]
> > 确认修复
> 
> 你试试精确模式，时间轴问题没解决

两个问题，您反馈的问题是字幕轴准确度产生偏差（不够精准），当前问题为“字幕轴乱序，下一个时间轴的字幕错为到了上一个时间轴”，这个问题已经修复了

**Comment by urna** [comment]
> > 确认修复
> 
> 你试试精确模式，时间轴问题没解决

我没有显卡，穷。。。快速模式适合我 。。
