### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by xuhui1994** [YaoFANGUK/video-subtitle-extractor#14]
![image](https://user-images.githubusercontent.com/35833743/123786121-eaace880-d90b-11eb-99c7-ee65be118aed.png)

环境已经安装好，运行报上图中的错误

**Comment by YaoFANGUK** [comment]
虽然paddle报successful了 但是出现segmentation fault一般就是cuda、cudnn和paddlepaddle的版本不匹配 请使用cuda 10.2+cudnn 7.6.5，用了cudnn 8一定报这个错

**Comment by xuhui1994** [comment]
> 虽然paddle报successful了 但是出现segmentation fault一般就是cuda、cudnn和paddlepaddle的版本不匹配 请使用cuda 10.2+cudnn 7.6.5，用了cudnn 8一定报这个错

因为我使用的服务器，如果换了cudnn，我怕会影响其他人使用，我能不能使用cudnn 8适配的paddle来运行这个程序？

**Comment by YaoFANGUK** [comment]
建议使用docker或Google colab

**Comment by xuhui1994** [comment]
非常感谢答疑
