### ISSUE TITLE
快速模式丢字幕问题

### ISSUE THREAD

**Issue by helloxuejuxi** [YaoFANGUK/video-subtitle-extractor#141]
真是诡异，发的问题贴居然不见了，是作者给删了吗？感谢开源，但现在时间轴精准模式还是不对，您可以自己试试，偏离太远了，快速模式时间轴准，但遗漏厉害

**Comment by helloxuejuxi** [comment]
还有一个诡异的地方，那就是在快速模式下，框选区域大小不同，识别出来的字幕条数居然还不一样，尽管都把文字包含进去了

**Comment by YaoFANGUK** [comment]
遗漏厉害是你参数没调对，config.py里面可以自己调参，subfinder里面settings的cfg也可以调参。发的贴不见了是因为你打广告

**Comment by helloxuejuxi** [comment]
> 遗漏厉害是你参数没调对，config.py里面可以自己调参，subfinder里面settings的cfg也可以调参。发的贴不见了是因为你打广告

感谢指点，我只是用过那个给你看一下人家的效果，对标人家的效果，打毛的广告，可笑，这么不自信吗？

**Comment by helloxuejuxi** [comment]
> 遗漏厉害是你参数没调对，config.py里面可以自己调参，subfinder里面settings的cfg也可以调参。发的贴不见了是因为你打广告

也就是说还需要手动调整很多参数对吧，不是说拿过来就能很好的用起来

**Comment by helloxuejuxi** [comment]
subfinder的参数默认字幕是居中对齐，因为我要提取的字幕是左对齐的，所以字幕比较短的那些用默认的居中对齐就漏掉了，修改为any就好了，已经没有遗漏，感谢指点。这样也就没必要用精准模式了，精准模式的时间戳问题您可以再检查一下。此外模型可能还是不够大，比如字幕中的“大都督”会识别成“天都督”，“舌战群雄”就会漏掉“舌”字，“鏖兵”识别为“兵”，这些问题不是很大，最重要的问题解决了，再次感谢

**Comment by YaoFANGUK** [comment]
> 

精准模式是每一帧都处理，然后每一帧都用DBNet检测有没有文本，相对于快速模型的传统图像算法找字幕，更不需依赖与参数的设置，鲁棒性更好，但是需要有很强大的显卡支持。 原来精准模式用的高精度的识别模型，现在快速也换用高精度的了。

**Comment by YaoFANGUK** [comment]
精准模式字幕轴的精度问题一直在优化，不准的根源在部分视频为可变帧率。非关键帧的地方，帧号转时间戳有偏差。如果是固定帧率算出来就不会有偏差。程序也不知道视频读取到某一位置时当前帧率是多少。

**Comment by helloxuejuxi** [comment]
> 精准模式是每一帧都处理，然后每一帧都用DBNet检测有没有文本，相对于快速模型的传统图像算法找字幕，更不需依赖与参数的设置，鲁棒性更好，但是需要有很强大的显卡支持。用传统的图像算法找字幕就是需要设置一堆参数的，可以看design里面的论文，里面有介绍。 另外原来精准模式用的高精度的识别模型，现在快速也换用高精度的了。

您说的高精度模型也就是那个大模型吧，大模型是相对fast来说的吗？我还没研究源码，回头细究下
