### ISSUE TITLE
经过多次测试，最新版的精准模式，无论字幕在中间还是左对齐，时间戳都不准

### ISSUE THREAD

**Issue by helloxuejuxi** [YaoFANGUK/video-subtitle-extractor#144]
经过多次测试，最新版的精准模式，无论字幕在中间还是左对齐，时间戳都不准，大佬看下啥情况，精准模式速度比以前快一倍

**Comment by YaoFANGUK** [comment]
不看

**Comment by YaoFANGUK** [comment]
你来定义下时间戳偏差多少以内才叫准

**Comment by helloxuejuxi** [comment]
精准模式不是偏差的问题了，您看下啊

**Comment by helloxuejuxi** [comment]
> 你来定义下时间戳偏差多少以内才叫准

精准模式不是偏差的问题了，您看下啊

**Comment by YaoFANGUK** [comment]
我用demo视频测试过的没遇到这个问题

**Comment by helloxuejuxi** [comment]
> 我用demo视频测试过的没遇到这个问题

我就用test_cn.mp4这个测的，您重新下载看看，是不是上传的时候传的版本不对

**Comment by YaoFANGUK** [comment]
你录个视频看看

**Comment by helloxuejuxi** [comment]
https://user-images.githubusercontent.com/83280021/177692975-576129a0-8a13-45fb-bc9f-cf029dc56d9c.mp4

**Comment by helloxuejuxi** [comment]
> 你录个视频看看

如上，您看下

**Comment by YaoFANGUK** [comment]
这叫不准吗….你要定义一下偏差多少耗秒内才叫准

**Comment by helloxuejuxi** [comment]
> 这叫不准吗….你要定义一下偏差多少耗秒内才叫准

快速模式几乎和原字幕分毫不差，达到这种就可以

**Comment by helloxuejuxi** [comment]
> 这叫不准吗….你要定义一下偏差多少耗秒内才叫准
达到这种下面才能用吧，至少上面那种不能为准，您再想一下，如果您再坚持我也没办法了
https://user-images.githubusercontent.com/83280021/177703393-e2ff9903-413f-41b4-ad77-9ae70a75a468.mp4

**Comment by YaoFANGUK** [comment]
不能用就别用啊，开源项目，有本事你自己写代码pr一个过来，一个大学生毕设项目对标商业软件干嘛，又没赚一份钱，没人开工资，全凭兴趣做。你要是我老板，定义10ms以内的偏差能接受，不然达不到验收标准，那我加班加点给你搞。

**Comment by eritpchy** [comment]
前排吃瓜

**Comment by helloxuejuxi** [comment]
> 不能用就别用啊，开源项目，有本事你自己写代码pr一个过来，一个大学生毕设项目对标商业软件干嘛，又没赚一份钱，没人开工资，全凭兴趣做。你要是我老板，定义10ms以内的偏差能接受，不然达不到验收标准，那我加班加点给你搞。

真是浮躁，听不得意见，再见，多说无益

**Comment by eritpchy** [comment]
快速模式是用图形学处理字幕帧的，精准模式是用ocr..而且还存在跳帧加速，每一帧都识别估计你的电脑都受不了(自己改配置), 如果ocr没识别到,时间轴就不准,如果刚好跳帧,不准，通常视频都是15～23帧左右，也就是一帧44～66ms BOOM! 继续吃瓜

**Comment by helloxuejuxi** [comment]
> 快速模式是用图形学处理字幕帧的，精准模式是用ocr..而且还存在跳帧加速，每一帧都识别估计你的电脑都受不了(自己改配置), 如果ocr没识别到,时间轴就不准,如果刚好跳帧,不准，通常视频都是15～23帧左右，也就是一帧44～66ms BOOM! 继续吃瓜

感谢指导，原以为作者是个精益求精的人，没想到戾气这么重，我只是指出来当前存在的问题，从来没说什么严重的话。说道ocr，其实也不用每一帧都检测识别，也可以跳跃，只不过有回溯的过程，一样可以实现精准，字幕起始帧的位置，完全可以匹配，我自己在写了。

**Comment by eritpchy** [comment]
你说得对呀，不用每帧都识别(这不就是快速模式吗?)
作者的脾气挺好的了，想当年我对接客户的时候见一个骂一个。

**Comment by helloxuejuxi** [comment]
> 你说得对呀，不用每帧都识别(这不就是快速模式吗?) 作者的脾气挺好的了，想当年我对接客户的时候见一个骂一个。

快速模式源码的处理逻辑也不符合，实际来看时间戳比精准模式好很多，但对标VSF模式，时间戳还是不准，因为是间隔取样放入队列，应该先取帧检测和识别，再间隔，顺序反了，所以这种快速模式时间戳也不精准，您看是吧

**Comment by eritpchy** [comment]
我说的就是快速VSF模式哦 你说的那种普通快速模式，是个人都知道他不准，1秒就捡3帧来识别能准到哪去。ps: 重复造轮子毫无意义，尤其是你的轮子还不一定如人家vsf开源的好

**Comment by eritpchy** [comment]
哪怕是vsf时间轴也不一定100%准的，你自己做过就知道了，各种各样的问题非常多。大佬，一年后见。来个100%准确率的开源高速提取字幕软件，最好能1分钟提取好一部电视剧。

还有什么间隔，什么回朔等等..，这些简单的想法我基本都测试过，兴高采烈写了几句，效果不好又删了，索然无味

**Comment by DidaDidaDidaD** [comment]
> 哪怕是vsf时间轴也不一定100%准的，你自己做过就知道了，各种各样的问题非常多。大佬，一年后见。来个100%准确率的开源高速提取字幕软件，最好能1分钟提取好一部电视剧。
> 
> 还有什么间隔，什么回朔等等..，这些简单的想法我基本都测试过，兴高采烈写了几句，效果不好又删了，索然无味

能达到VSF这种就可以，linux下不是不支持么？我不是大佬，刚接触，说下想法而已，结贴

**Comment by eritpchy** [comment]
别说linux, mac也不支持， mac才是大户，用linux基本都是商业化的，想商业化，自己想办法, 不过mac版本我有写好apple vision的版本， win版本也可以商业化，代码一个月前我都码好了，鬼知道我这个月在干嘛. 不然你们就有免费的在线字幕提取软件用了

**Comment by eritpchy** [comment]
什么叫达到vsf，你知道人家vsf作者做了几年吗。当然我很欢迎你去吧vsf移植到linux mac,这样我apple vision版字幕提取器就*了

**Comment by DidaDidaDidaD** [comment]
> 什么叫达到vsf，你知道人家vsf作者做了几年吗。当然我很欢迎你去吧vsf移植到linux mac,这样我apple vision版字幕提取器就*了

我水平有限，github上好像有c++源码，可以在linux上编译看看，暂时我不打算折腾这块

**Comment by YaoFANGUK** [comment]
抱歉，最近戾气很重，维护项目是花时间精力的，有些东西一直在优化，都是抽业余时间搞的。缺陷控制在一定范围内就可以认为是可用的，比如ocr模型准确度达到98%以上甚至95%就已经认为可用，科研和投产对缺陷的要求又是不一样的，希望你能理解开源开发者，况且我也没有很久的开发经验，属于初级开发，不要要求一个开源项目做到商业化软件的水平。没达到要求你的程度就说不可用，否定这个项目价值会很打击开源开发者的。

你之前提过几个issue，上来就是丢字幕“太厉害了”，错字“太多了”，“xxx分钟的视频识别也要xxx分钟，太久了”，“时间线”非常不准，比不上xxx软件，“xxx问题不该发生”，就是抱着挑刺的语气来的。我做个开源项目我还被迫当乙方，心里自然不舒服。你要是我的客户我承认我态度有问题，也不会对你说这些。但是开发者之间不该这样挑人刺的交流。


VSF的开源代码在这里 https://sourceforge.net/p/videosubfinder/src/ci/master/tree/

**Comment by DidaDidaDidaD** [comment]
> 抱歉，最近戾气很重，维护项目是花时间精力的，有些东西一直在优化，都是抽业余时间搞的。缺陷控制在一定范围内就可以认为是可用的，比如ocr模型准确度达到98%以上甚至95%就已经认为可用，科研和投产对缺陷的要求又是不一样的，希望你能理解开源开发者，况且我也没有很久的开发经验，属于初级开发，不要要求一个开源项目做到商业化软件的水平。没达到要求你的程度就说不可用，否定这个项目价值会很打击开源开发者的。
> 
> 你之前提过几个issue，上来就是丢字幕“太厉害了”，错字“太多了”，“xxx分钟的视频识别也要xxx分钟，太久了”，“时间线”非常不准，比不上xxx软件，“xxx问题不该发生”，就是抱着挑刺的语气来的。我做个开源项目我还被迫当乙方，心里自然不舒服。你要是我的客户我承认我态度有问题，也不会对你说这些。但是开发者之间不该这样挑人刺的交流。
> 
> VSF的开源代码在这里 https://sourceforge.net/p/videosubfinder/src/ci/master/tree/

感谢，没有任何恶意，只是提个建议可以搞的更好，毕竟工作都做了这么多了。或许之前的言辞确实让人容易产生误会，抱歉。
