### ISSUE TITLE
优化识别次数80%，请教如何用容器运行您的代码

### ISSUE THREAD

**Issue by m986883511** [YaoFANGUK/video-subtitle-extractor#15]
我在win10上直接跑是可以运行的，识别率很高，比Tesseract好很多，就是比较慢 ；
我的环境：nvidia-smi 11.4 nvcc 11.1 GTX1660s，win10，cpu=10400
我在识别之前做了一些优化，可以减少识别次数，提高速度。
这是我写的pyqt5界面，没写完，里面有下面前两步的代码：
https://gitee.com/m986883511/python_demo/blob/master/%E5%AD%97%E5%B9%95%E7%A1%AC%E6%8F%90%E5%8F%96/main.py

1、FFMPEG提取视频音频
2、spleeter separate分离音频人声
3、pydub中的detect_nonsilent方法，按照停顿切割音频并定位时间点
4、根据时间点使用您的代码识别字幕

这样做之后，一段字幕因语音停顿最多只会识别3次，可以将识别次数大约减少80%

我想做个容器直接部署就能运行您的程序，
我只是个自动化脚本工程师，深度学习并不深入，很多报错看不懂，我想做个容器封装您的程序，然后通过flask写个api，图片通过base64编码传输，这样就能调用后台了，容器传播也方便。

我在ufoym/deepo:cpu的docker容器中运行报错（win10）

![image](https://user-images.githubusercontent.com/34444109/126059515-4693e859-66d3-4330-a8e6-c3fd104e9b03.png)

您前面有回答过是cudnn和cuda版本不兼容导致的，有傻瓜式直接用的环境镜像吗？
这是我找到的镜像仓库：https://hub.docker.com/r/ufoym/deepo/tags?page=1&ordering=last_updated
我的电脑上的深度学习环境好不容易装上，真的不想换版本，能在windows上用容器运行您的cpu版本吗？ubuntu也行。

**Comment by YaoFANGUK** [comment]
推荐用英伟达带cuda的官方docker镜像 cudnn 7.6 cuda 10.2

**Comment by m986883511** [comment]
> 推荐用英伟达带cuda的官方docker镜像 cudnn 7.6 cuda 10.2

有链接吗

**Comment by m986883511** [comment]
非常感谢，我使用这个镜像可以了，
docker pull nvidia/cuda:10.2-cudnn7-devel-centos8
![image](https://user-images.githubusercontent.com/34444109/126068216-b6ef545d-aa31-437e-90d6-7a8abc766d33.png)

感觉镜像里面运行，速度也挺快的

**Comment by m986883511** [comment]
我做出来了，项目地址https://github.com/m986883511/extract-video-subtittle
