### ISSUE TITLE
SRT output file format is invalid

### ISSUE THREAD

**Issue by JohnMalvern** [YaoFANGUK/video-subtitle-extractor#151]
The subrip subtitle format spec specifies three digits for milliseconds.
video-subtitle-extractor is writing only two digits.
Example test output:
1
00:00:01,00 --> 00:00:03,06
因特福罗成立于三十年代

2
00:00:03,14 --> 00:00:05,20
是一家历史悠久的意大利企业

The millisecond values are ambiguous like this and not all software can read the file because the spec says 3 digits for milliseconds.
For example is the 14 above (in  00:00:03,14) supposed to be 140mS or 014mS?

**Comment by YaoFANGUK** [comment]
Thank you for your feedback. I will fix it soon.
