### ISSUE TITLE
APU+Tesla P4  时 GPU 不参加工作

### ISSUE THREAD

**Issue by sam-johnson** [YaoFANGUK/video-subtitle-extractor#152]
如图。

环境：
(1):Windows10 x64
(2)Nvidia Driver Ver :  516.94-data-center-tesla-desktop-win10-win11-64bit-dch-international
(3)CUDA Ver :  cuda_11.7.1_516.94_windows
(4)cuDNN Ver : cudnn-windows-x86_64-8.5.0.96_cuda11-archive

![888](https://user-images.githubusercontent.com/11351908/184111805-fca78dbe-09e4-473d-8d10-2bc1e53ebf28.png)

**Comment by YaoFANGUK** [comment]
你软件版本太低了

**Comment by sam-johnson** [comment]
请问最新版GPU的是这个文件吗：
https://github.com/YaoFANGUK/video-subtitle-extractor/releases/download/1.0.0/vse_windows_GPU.7z

**Comment by YaoFANGUK** [comment]
嗯嗯

**Comment by sam-johnson** [comment]
问题依旧，我用了次源码方式，在安装 paddlepaddle 时 发现暂时还没有 CUDA 11.7 版本的支持，所以安装完后出现以下信息：
【 “W0811 19:12:35.018816  3604 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 11.6”】
感觉是Runtime API version 为11.6 过低 不匹配。

同时出现以下提示：

Could not locate zlibwapi.dll. Please make sure it is in your library path!

分析：由于对您的软还不太了解，感觉是因为CUDA版本不匹配的问题。不知是否感觉正确。

**Comment by YaoFANGUK** [comment]
paddlepaddle的版本和cuda和cudnn不匹配，建议按照教程的版本安装，别的版本没试过

**Comment by sam-johnson** [comment]
> paddlepaddle的版本和cuda和cudnn不匹配，建议按照教程的版本安装，别的版本没试过

我已经解决了没有，用最新的 2.3.1 post11 + CUDA 11.7 +cuD padNN 8.5 测试后正常问题。反正全是官方使用的最新版。 paddle10月会出
CUDA 11.7官方支持。
