### ISSUE TITLE
Is there a custom training guideline with this repository?

### ISSUE THREAD

**Issue by kangyeolk** [YaoFANGUK/video-subtitle-extractor#167]
Thank you for your awesome work!
I wonder that if I can train my own model and use it during inference.
Thank you!

**Comment by YaoFANGUK** [comment]
plz see: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/training_en.md

**Comment by kangyeolk** [comment]
Thank you!
