### ISSUE TITLE
谷歌colab用不了呀？

### ISSUE THREAD

**Issue by wg1929** [YaoFANGUK/video-subtitle-extractor#168]
试了几次都不能提取了。

![image](https://user-images.githubusercontent.com/21093017/200113593-76436a84-6ccd-4ed3-91fb-fdb036690556.png)

**Comment by wg1929** [comment]
字幕区域 加入 和 不加入 两种都试几次。

**Comment by HyperSimon** [comment]
相同的问题

**Comment by YaoFANGUK** [comment]
修复了，再试下。 colab更新底层cudnn库到11.2导致的
