### ISSUE TITLE
German subtitles?

### ISSUE THREAD

**Issue by robertvank** [YaoFANGUK/video-subtitle-extractor#186]
Thanks so much for an excellent program, it's super useful. I'm just having some problems extracting German subtitles, using the Windows CPU version. It freezes about halfway through. 
If I set the language to English, it *does* complete the extraction, but all the specific German letters need correction, a lot of work! 
Is there some filter or add-on that I need to get hold of? Any advice very welcome! Thanks, Robert

**Comment by maxminstr** [comment]
I can confirm this issue with German language. While English works fine, German hangs about halfway through.

It'd be great if a fix was available as having the German language working would enable using this great tool much better also with some other languages (such as Swedish and Finnish).

**Comment by YaoFANGUK** [comment]
Fixed, please use the latest source code.

**Comment by robertvank** [comment]
Thanks!

Robert
