### ISSUE TITLE
mac版用原生“实况文字”功能来识别提取文字？

### ISSUE THREAD

**Issue by snodr** [YaoFANGUK/video-subtitle-extractor#188]
mac版是否可以改用原生的“实况文字”功能来识别提取文字？

https://developer.apple.com/documentation/vision/recognizing_text_in_images/

**Comment by eritpchy** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/8630635/220313127-8ca06c48-d2da-42e9-816a-6fbe3199182a.png">
