### ISSUE TITLE
google colab 安装 paddle 版本遇到问题，麻烦看下

### ISSUE THREAD

**Issue by YoungKang1222** [YaoFANGUK/video-subtitle-extractor#189]
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.3.2.post112 (from versions: 1.8.5.post97, 1.8.5.post107, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0, 2.4.1, 2.4.2)
ERROR: No matching distribution found for paddlepaddle-gpu==2.3.2.post112

![image](https://user-images.githubusercontent.com/30460985/220512045-007091a2-dcba-4148-b35a-0f7ffa9a5082.png)

**Comment by YaoFANGUK** [comment]
python -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by YoungKang1222** [comment]
谢谢回复
