### ISSUE TITLE
Dont work !

### ISSUE THREAD

**Issue by Lordness** [YaoFANGUK/video-subtitle-extractor#19]
![image](https://user-images.githubusercontent.com/20818167/128799936-8918c16f-611d-4e43-8552-5e9c79491d12.png)

**Comment by YaoFANGUK** [comment]
Cloud you please specify where the errors are ?  LGTM

**Comment by Lordness** [comment]
no gui open dont know how that work

**Comment by YaoFANGUK** [comment]
Can you just run ```main.py```? Which python do you use? (you can try ```python3 gui.py```) I need no infomation to location the problem.

**Comment by Lordness** [comment]
![image](https://user-images.githubusercontent.com/20818167/128818001-096ffbfa-18b4-4607-856c-a6c91b06589d.png)

**Comment by YaoFANGUK** [comment]
It looks like your python was not found. You need add python to environment variables.

**Comment by Lordness** [comment]
![image](https://user-images.githubusercontent.com/20818167/128823391-8cabde49-7913-4c38-83b0-6ed73322898d.png)

**Comment by Lordness** [comment]
how to add python to env variable ?

**Comment by YaoFANGUK** [comment]
This is wierd.... Did you just get stuck here? Could you please add my Whatsapp account(+86 13161666577) and send a video clip to me so that I can help you with this.

**Comment by YaoFANGUK** [comment]
It looks fine when the "runing Verify Fluid Program .." is printed. However, if the program is then frozen without a gui displayed, it's wierd...

**Comment by YaoFANGUK** [comment]
If you get stuck in "running Verify Fluid Program", you can just delete ```fluid.install_check.run_check()``` in ```config.py```

**Comment by Lordness** [comment]
> If you get stuck in "running Verify Fluid Program", you can just delete `fluid.install_check.run_check()` in `config.py`

Thanks work now
