### ISSUE TITLE
請檢查Merge pull request #195 from eritpchy/patch-16後出現的NameError: name 'Filesplit' is not defined

### ISSUE THREAD

**Issue by hkuhku609** [YaoFANGUK/video-subtitle-extractor#197]
<img width="1029" alt="Screenshot 2023-03-29 at 14 36 14" src="https://user-images.githubusercontent.com/107769663/228555612-d1ea07b3-cb37-49f0-8581-5f7ded293be4.png">
如題

**Comment by eritpchy** [comment]
@YaoFANGUK 192这块代码有啥用, 要不整块删了? 而且他是怎么跑进这块代码的?

**Comment by eritpchy** [comment]
> @YaoFANGUK 192这块代码有啥用, 要不整块删了? 而且他是怎么跑进这块代码的?

明白了, 所以说CH fast v3是没有用的...

**Comment by eritpchy** [comment]
fixed https://github.com/YaoFANGUK/video-subtitle-extractor/pull/198

**Comment by hkuhku609** [comment]
> fixed #198
你fixed後檢查過google能正常運行？

**Comment by YaoFANGUK** [comment]
prove fixed
