### ISSUE TITLE
可以使用tesseract 5.3.1进行文字识别吗？

### ISSUE THREAD

**Issue by lapi2023** [YaoFANGUK/video-subtitle-extractor#206]
很高兴找到了这么好的项目，我也尝试了一下效果非常好。
可是在日语识别上感觉还是有上升的空间，
不知能否使用Tesseract(https://github.com/tesseract-ocr/tesseract)等多种引擎进行文字识别呢？

I am glad to find such a good project and I have tried it with very good results.
However, I feel that there is still room for improvement in Japanese recognition.
I wonder if it is possible to use Tesseract (https://github.com/tesseract-ocr/tesseract) and other engines for text recognition?

**Comment by YaoFANGUK** [comment]
tessetact巨辣鸡

**Comment by rdcyuxi** [comment]
tessetact巨辣鸡 +1
