### ISSUE TITLE
Please compile with GPU to EnableGpu()

### ISSUE THREAD

**Issue by Altansar69** [YaoFANGUK/video-subtitle-extractor#207]
(videoEnv) D:\repos>python gui.py
Running Verify Fluid Program ...
Your Paddle Fluid works well on SINGLE GPU or CPU.
W0419 01:10:53.052335 10784 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 1.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
2560 1440
E0419 01:11:52.367136 14576 analysis_config.cc:91] Please compile with gpu to EnableGpu()

The program works but according to the last line my gpu is not taken into account. How can I compile with the gpu?
By the way, thank you so much for your program, I've been looking for a program to do this for so long.

**Comment by YaoFANGUK** [comment]
if you have nvidia gpu，please use 
```
pip install paddlepaddle-gpu
```

**Comment by Altansar69** [comment]
Nice thx

**Comment by Altansar69** [comment]
I need to do that on the conda  videoEnv  ? Or "normally" on my PC ?

**Comment by YaoFANGUK** [comment]
conda videoEnv

**Comment by Altansar69** [comment]
ok, thx !
