### ISSUE TITLE
用的GPU加速版，一部3小时的视频，处理了6个半小时才处理50%

### ISSUE THREAD

**Issue by noir1216** [YaoFANGUK/video-subtitle-extractor#218]
这速度也太慢了吧
![QQ截图20230713212557](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/44556349/95ad0efd-de63-478a-8700-05c5bf0a5629)

**Comment by eritpchy** [comment]
出错了

**Comment by eritpchy** [comment]
用不了GPU

**Comment by noir1216** [comment]
> 用不了GPU

看cmd里的信息，gpu加速环境配置成功了的呀，为什么会用不了gpu呢

**Comment by Jay921027** [comment]
![image](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/133524232/284b6557-e266-4a9e-9f2b-f4052c757313)
![image](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/133524232/79b25a9c-2f0a-4c7d-986d-5d136b1c4ebe)

這邊也有同樣的問題，精準模式一部20幾分鐘的動畫跑了一整晚才到1/3，這樣是正常的嗎?
配備是i7-12700H + RTX3050，GPU占用率一下高一下低的，謝謝

**Comment by LuiYang08** [comment]
i7-12650H + RTX4060 笔记本，10分钟的视频，字幕提取用了519s（将近9分钟），不知道算不算正常

**Comment by yalik01** [comment]
别的软件OCR识别图片文字都秒出来，是不是识别思路有问题。

**Comment by YaoFANGUK** [comment]
用的2.0的版本？ 运行的时候有打印使用gpu加速吗

**Comment by eritpchy** [comment]
60分钟视频10系列显卡不到10分钟识别完成路过

**Comment by noir1216** [comment]
> 用的2.0的版本？ 运行的时候有打印使用gpu加速吗

我这是2个月前的问题。刚刚看了眼，2.0的4天前才发布

**Comment by LuiYang08** [comment]
> 60分钟视频10系列显卡不到10分钟识别完成路过

差距那么大的吗？
