### ISSUE TITLE
Change gui language

### ISSUE THREAD

**Issue by KeyMan98** [YaoFANGUK/video-subtitle-extractor#219]
How can I change the language from Chinese to English? I downloaded GPU version 1.0.0
![Screenshot 2023-07-22 003102](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/78966959/cbbbeb9c-1c08-48c5-9f15-ee8f89a79c75)

**Comment by KeyMan98** [comment]
Solved

![image](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/78966959/68097687-6cc5-482b-816b-7825635e52c2)

**Comment by Nemesisita** [comment]
How can I change the language from Chinese to English? I downloaded Single-file Windows version (vse.exe)
