### ISSUE TITLE
./VideoSubFinderCli: error while loading shared libraries: libpcre2-32.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yuzhiyizhan** [YaoFANGUK/video-subtitle-extractor#225]
最开始报这个错
./VideoSubFinderCli: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory

安装ffmpeg 4.2.9后 新的报错

./VideoSubFinderCli: error while loading shared libraries: libpcre2-32.so.0: cannot open shared object file: No such file or directory

请问如何解决

**Comment by YaoFANGUK** [comment]
修复了，用最新版本的代码
