### ISSUE TITLE
使用2.0版本未调用GPU ，大佬帮看看是什么情况

### ISSUE THREAD

**Issue by shui9527** [YaoFANGUK/video-subtitle-extractor#248]
下载更新了2.0版本，结果发现部署有报错。尝试运行发现没有调用gpu。
求大佬指导一下如何解决

D:\vse>"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');from qpt.run import module;module.run('""')"
D:\vse\Python\Lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
→[2023-10-22 11:03:46,694] [INFO] | QPT Runtime版本号为1.0b4.dev6，若无法使用该程序，可向程序发布者或GitHub: QPT-Family/QPT提交issue寻求帮助
→[2023-10-22 11:03:47,524] [INFO] | 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度-22 114/8  |━━━━━━━━━━          | 50.00% NoneName_paddlepaddle-gpu部署中...→[2023-10-22 11:04:21,940] [INFO] 初始化进度      6/8  |━━━━━━━━━━━━━━━     | 75.00% PaddlePaddleCheckAVX部署中...D:\vse\Python\Lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
D:\vse\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\vse\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
→[2023-10-22 11:05:02,830] [WARNING] | No module named 'paddle.fluid.core_avx'
→[2023-10-22 11:05:02,830] [WARNING] | 为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX
→[2023-10-22 11:05:02,830] [WARNING] | 当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle
→[2023-10-22 11:05:05,596] [ERROR] | 在执行终端命令时检测到了失败，完整信息如下：
PS D:\vse> cd D: ;D:\vse\Python\python.exe -m pip install paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\shuis\AppData\Local\Temp\QPT_Cache_V/1.0b4.dev6\pip_cache --timeout 10 --prefer-binary --quiet; echo "---QPT OUTPUT STATUS CODE---" ;$?
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\vse\\Python\\Lib\\site-packages\\paddle\\fluid\\libpaddle.pyd'
Consider using the `--user` option or check the permissions.

初始化进度-22 117/8  |━━━━━━━━━━━━━━━━━   | 87.50% 初始化完毕→[2023-10-22 11:05:05,596] [INFO] | ----------WARNING SUMMARY
→[2023-10-22 11:05:05,596] [INFO] | 0|No module named 'paddle.fluid.core_avx'

→[2023-10-22 11:05:05,597] [INFO] | 1|为保证可以成功在NoAVX平台执行PaddlePaddle，即将忽略小版本号进行安装PaddlePaddle-NoAVX

→[2023-10-22 11:05:05,597] [INFO] | 2|当前CPU不支持AVX指令集，正在尝试在线下载noavx版本的PaddlePaddle

→[2023-10-22 11:05:05,597] [INFO] | ----------ERROR SUMMARY
→[2023-10-22 11:05:05,597] [INFO] | 3|在执行终端命令时检测到了失败，完整信息如下：
PS D:\vse> cd D: ;D:\vse\Python\python.exe -m pip install paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps --force-reinstall --isolated --disable-pip-version-check --cache-dir C:\Users\shuis\AppData\Local\Temp\QPT_Cache_V/1.0b4.dev6\pip_cache --timeout 10 --prefer-binary --quiet; echo "---QPT OUTPUT STATUS CODE---" ;$?
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\vse\\Python\\Lib\\site-packages\\paddle\\fluid\\libpaddle.pyd'
Consider using the `--user` option or check the permissions.

→[2023-10-22 11:05:05,597] [INFO] | ----------生成状态WARNING:3 ERROR:1
PS D:\vse> cd "D:\vse\resources";./../Python/python.exe "D:\vse\resources\gui.py"  ; echo "---QPT OUTPUT STATUS CODE---" $?
D:\vse\Python\Lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
D:\vse\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\vse\Python\Lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\vse\Python\Lib\site-packages\paddle\distributed\parallel.py:87: SyntaxWarning: "is" with a literal. Did you mean "=="?
  ) or backend is 'xccl':
D:\vse\Python\Lib\site-packages\paddle\distributed\fleet\meta_parallel\sharding\group_sharded_optimizer_stage2.py:208: DeprecationWarning: invalid escape sequence \.
  "The param name passed to the optimizer doesn't follow .+_[0-9]+\..+ patter, "
D:\vse\Python\Lib\site-packages\paddle\dataset\common.py:38: DeprecationWarning: invalid escape sequence \T
  """
Running Verify Fluid Program ...
W1022 11:05:21.043167 19352 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.7
W1022 11:05:21.051070 19352 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Your Paddle Fluid works well on SINGLE GPU or CPU.
Your Paddle Fluid works well on MUTIPLE GPU or CPU.
Your Paddle Fluid is installed successfully! Let's start deep Learning with Paddle Fluid now
2560 1440

硬件情况
CPU ：Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz   2.90 GHz
显卡：NVIDIA GeForce RTX 3070

截图：
![git1](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/89987271/8dd302ee-7783-4da5-8489-d5a20c1d7f3c)

**Comment by YaoFANGUK** [comment]
打印了“使用GPU加速”就是调用了的

**任务管理器看不到cuda使用情况！**
**任务管理器看不到cuda使用情况！！**
**任务管理器看不到cuda使用情况！！！**

不信自己下个CPU版本对比

**Comment by YaoFANGUK** [comment]
打印了“使用GPU加速”就是调用了的

**任务管理器看不到cuda使用情况！**
**任务管理器看不到cuda使用情况！！**
**任务管理器看不到cuda使用情况！！！**

不信自己下个CPU版本对比

**Comment by bitxeno** [comment]
记得是前面截屏阶段要使用cpu跑，只有识别部分才跑gpu
