### ISSUE TITLE
very slow speed for fast mode

### ISSUE THREAD

**Issue by PickleSour** [YaoFANGUK/video-subtitle-extractor#252]
in the previous version, fast mode took less than 100 sec for 6 min. video. Now, it's taking more than 800 sec.

my pc (32gb ram + rtx 3060ti)

**Comment by YaoFANGUK** [comment]
because I updated more accurate model for fast mode. If you wanna use old model for fast speed, you can edit config.py and modify 162-163 line to:

```python
if USE_GPU:
    DET_MODEL_PATH = os.path.join(DET_MODEL_BASE, 'V4', 'ch_det_fast')

```

**Comment by YaoFANGUK** [comment]
This is a bug and I just fixed. Please use latest version with 1.99GB released on Nov. 1st 2023

**Comment by YaoFANGUK** [comment]
See #255
