### ISSUE TITLE
 系统找不到指定的路径

### ISSUE THREAD

**Issue by yaxiaxiaxia** [YaoFANGUK/video-subtitle-extractor#260]
下的最新的2.0的gpu版本，执行后提示错误：
 FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\vse\\resources\\backend\\models\\V3\\ch_det'

1.0的gpu版本则没有这个问题，是什么原因造成的呢？

**Comment by YaoFANGUK** [comment]
运行的什么模式 选的什么语言

**Comment by yaxiaxiaxia** [comment]
> 运行的什么模式 选的什么语言

精准模式  俄语

**Comment by yaxiaxiaxia** [comment]
> .0的gpu版本则没有这个问题，是什么原

测试了下英文字的精准识别，没有出现这个错误

**Comment by yaxiaxiaxia** [comment]
完整错误提示：
2023-11-10 09:54:36,460 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\vse_windows_gpu_v2.0.0\vse> cd "D:\vse_windows_gpu_v2.0.0\vse\resources";./../Python/python.exe "D:\vse_windows_gpu_v2.0.0\vse\resources\gui.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "D:\vse_windows_gpu_v2.0.0\vse\resources\gui.py", line 8, in <module>
    import backend.main
  File "D:\vse_windows_gpu_v2.0.0\vse\resources\backend\main.py", line 25, in <module>
    import config
  File "D:\vse_windows_gpu_v2.0.0\vse\resources\backend\config.py", line 193, in <module>
    if 'inference.pdiparams' not in (os.listdir(DET_MODEL_PATH)):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\vse_windows_gpu_v2.0.0\\vse\\resources\\backend\\models\\V3\\ch_det'


D:\vse_windows_gpu_v2.0.0\vse>pause
Press any key to continue . . .

**Comment by YaoFANGUK** [comment]
修复了，重新下载一下11.10号后的.7z压缩包

**Comment by yaxiaxiaxia** [comment]
> 修复了，重新下载一下11.10号后的.7z压缩包

谢谢大佬 辛苦了！
