### ISSUE TITLE
Warning - Github: QPT-Family/QPT

### ISSUE THREAD

**Issue by li1kj** [YaoFANGUK/video-subtitle-extractor#278]
将Windows系统默认编码改为UTF-8后仍然报同样的错误，请问如何解决？

![Screenshot 2023-12-14 035609](https://github.com/YaoFANGUK/video-subtitle-extractor/assets/105518002/c003c578-1024-4e75-a3e1-b37445408e8e)
谢谢！

**Comment by YaoFANGUK** [comment]
New Folder中间的空格删掉
