### ISSUE TITLE
输出文件为空

### ISSUE THREAD

**Issue by luogu-oddy** [YaoFANGUK/video-subtitle-extractor#341]
我使用的是 2.0.0 版本。我试图用 fast 模式为一段约 9 min 的视频提取字幕。它看似正常地工作了 2.5 min，之后输出了 srt 文件，但是文件为空，没有任何字符。我已经按照要求安装了 CUDA 和 cuDNN，但没有任何帮助。
我的系统是 Windows 10，显卡是 Intel UHD Graphics。
求助……

**Comment by Victor0717** [comment]
你这个是核显装gpu版没用，试试cpu版本

**Comment by luogu-oddy** [comment]
> 你这个是核显装gpu版没用，试试cpu版本

@Victor0717 我用的就是 cpu 版本。

**Comment by vivodi** [comment]
CPU版本不需要CUDA 和 cuDNN，CUDA和cuDNN都是Nvidia的东西
