### ISSUE TITLE
生成关键帧的问题

### ISSUE THREAD

**Issue by dfmjndm** [YaoFANGUK/video-subtitle-extractor#43]
在生成关键帧卡了很长时间，CPU100%，GPU没有动，生成结束后才开始使用GPU，可以优化吗

**Comment by YaoFANGUK** [comment]
用的什么版本的

**Comment by dfmjndm** [comment]
> 用的什么版本的

git clone了现在的仓库，配置文件把GPU开了，处理的文件是300M的视频，在生成关键帧这一项后台看到跑的是CPU

**Comment by YaoFANGUK** [comment]
提取关键帧用不到gpu的

**Comment by xinxin8816** [comment]
可以参考 [video-timeline-and-subtitle-extract](https://github.com/drsanwujiang/video-timeline-and-subtitle-extract/blob/master/opencv.py) 的实现，比调用 subfinder 效率高很多
