### ISSUE TITLE
CPU版本运行卡住了

### ISSUE THREAD

**Issue by royzengyi** [YaoFANGUK/video-subtitle-extractor#46]
我的电脑是集成显卡，所以运行的CPU版本，在选好字幕区域后，点击运行，消息框中显示[处理中]开启提取关键帧，然后就没下文了...命令行窗口显示E1202 16:07:26.463443 16968 analysis_config.cc:91] Please compile with gpu to EnableGpu()...e[37m---    fused 0 pairs of fc gru patternse[0m
等了十分钟都没动静. 但进程一直在运行，CUP占用33%左右，内存占用1.8G左右...
大神帮忙分析下是什么问题呢？

**Comment by YaoFANGUK** [comment]
你耐心等一下不就好了

**Comment by royzengyi** [comment]
已经50多分钟了,还卡在那里。是不是CPU版本不能选精准识别？
![02](https://user-images.githubusercontent.com/47094585/144391762-0cadb07d-5343-4ba2-b774-d95abad01500.png)

**Comment by YaoFANGUK** [comment]
没有卡住 试运行很慢，cpu用精准模式都是以天为单位的，五十分钟1%的进度都没

**Comment by royzengyi** [comment]
了解了，谢谢解答
