### ISSUE TITLE
GPU版本不能运行（CUDNN库找不到）

### ISSUE THREAD

**Issue by royzengyi** [YaoFANGUK/video-subtitle-extractor#48]
CUDN及CUDNN已经配置好环境且测试通过，如下图
![02](https://user-images.githubusercontent.com/47094585/145042430-21199cf2-f572-494d-b804-021f58ece379.png)
但运行GPU版本时仍然报错说找不到CUDNN库
![03](https://user-images.githubusercontent.com/47094585/145042713-b328594e-1c66-42f4-89a7-1d566765f636.png)
我发现好像是版本问题，我是GTX1650 TI的显卡，按照说明装的是cudn10.1和cudnn-7.6.5，对应的库应该是cudnn64_7.dll
但GPU版本报错说找不到cudnn64_8.dll, 这个肯定是没有的，GPU版本默认找cudnn-8+吗？
麻烦作者帮忙指点下怎么改呢？

**Comment by YaoFANGUK** [comment]
只支持安装CUDA 11.2和cuDNN 8.1.1，其他版本没用，并不是版本越高越高。不向下兼容的

**Comment by royzengyi** [comment]
好的，我重装了CUDA 11.2和cuDNN 8.1.1能正常运行了，比CPU版本快了很多，非常感谢！
