### ISSUE TITLE
识别英语单词会位置错乱

### ISSUE THREAD

**Issue by jbue520** [YaoFANGUK/video-subtitle-extractor#51]
识别出一句话，比如 That was a great idea, right? 他识别出就会变成 That right? a great idea, right? was 或者 Thatwasa great idea, right?

**Comment by eritpchy** [comment]
这个问题已经暂时在我的版本中优化 欢迎围观

**Comment by jbue520** [comment]
> 这个问题已经暂时在我的版本中优化 欢迎围观

额...可以分享么？

**Comment by eritpchy** [comment]
你点我的账号里的项目就在里面，我手机不方便

**Comment by jbue520** [comment]
> 你点我的账号里的项目就在里面，我手机不方便

不好意思..我点进去看到是同一个程序.. 我不太会怎么操作..

**Comment by eritpchy** [comment]
哈哈我只能帮你到这了

**Comment by jbue520** [comment]
> 
...残忍...

**Comment by eritpchy** [comment]
超级忙！🤣

**Comment by YaoFANGUK** [comment]
新版本已修复
