### ISSUE TITLE
Using wordninja to split the words

### ISSUE THREAD

**Issue by Dnkhatri** [YaoFANGUK/video-subtitle-extractor#54]
This works great but the problem I have is that a lot of text is just a long string of text instead of individual words. I was wondering if you could maybe implement this https://github.com/keredson/wordninja into your program so that the output result is better.

**Comment by YaoFANGUK** [comment]
Thank you for your suggestion. I will implement it within a week. Problem will be solved in 0.3.x version

**Comment by YaoFANGUK** [comment]
“wordninja” is a little bit out-dated. So I use “wordsegment” library instead. Now you can try the latest code. I will make distribution in few days.

**Comment by Dnkhatri** [comment]
Thanks I will wait for the distribution as checking out from git is a bit complicated for me.

**Comment by YaoFANGUK** [comment]
v0.3.0 distribution is now released.
