### ISSUE TITLE
Ablity to set video start and end time for accurate option

### ISSUE THREAD

**Issue by Dnkhatri** [YaoFANGUK/video-subtitle-extractor#59]
For the fast option it is not that important but when using  the accurate option the ability to set the video start & stop is needed as the software takes so long to scan those parts but they are actually pointless.

**Comment by YaoFANGUK** [comment]
It will be added in feature plan

**Comment by ruohai0925** [comment]
This will be a very useful and important feature. Support it!

**Comment by YaoFANGUK** [comment]
will implement it when this project get 1k stars.......
