### ISSUE TITLE
Upgrade Requirements

### ISSUE THREAD

**Issue by latot** [YaoFANGUK/video-subtitle-extractor#62]
Hi hi, I was installing the requimenets of the app, and I notice it have a old versions of packages, even some of them are not available any more:

```
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.0.1 (from versions: 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0rc0, 2.2.0, 2.2.1)
ERROR: No matching distribution found for paddlepaddle==2.0.1
```

This is not the only old package, numpy have some time too, this as an active project, I think would be great upgrade them.

Thx.

**Comment by YaoFANGUK** [comment]
done, thank you for your suggestions

**Comment by latot** [comment]
I tested now the app with all packages upgraded to their last version, and works fine!, do you have unit test here? I can test it and send a PR, if not, I can send the pr and you can try it.
