### ISSUE TITLE
请问如何在python中调用使用呢？

### ISSUE THREAD

**Issue by cherryoyo** [YaoFANGUK/video-subtitle-extractor#66]
你好，我还是个初学者，我测试了一下win下cpu版本的exe，发现识别率还不错。非常感谢作者能写出这么好的软件。
但是在使用过程中，由于我对python还不是特别的熟悉，所以在没有示例的情况下，实在不知道如何调用。

我想批量识别多个视频文件后生成srt字幕，请问您的代码如何在python文件中调用呢，能否提供python中调用的实例代码呢？

**Comment by YaoFANGUK** [comment]
你想识别几个文件你就双击几次exe文件

**Comment by cherryoyo** [comment]
exe执行还是有些不太方便的。
首先，文件比较多。
另外，我也想把它放到python中，通过运行py文件的方式运行，这样也更加灵活。

**Comment by YaoFANGUK** [comment]
那你为啥不直接运行我的源码，这个项目就是一个python项目啊

**Comment by Leonhardt92** [comment]
> exe执行还是有些不太方便的。 首先，文件比较多。 另外，我也想把它放到python中，通过运行py文件的方式运行，这样也更加灵活。

改下, main.py文件就行了

**Comment by cherryoyo** [comment]
比如moviepy，我是看了示例代码后，会使用了。
作者提供的有类似这样的示例代码：
from moviepy import *

video = VideoFileClip("myHolidays.mp4").subclip(50,60)

# Make the text. Many more options are available.
txt_clip = ( TextClip("My Holidays 2013",fontsize=70,color='white')
             .with_position('center')
             .with_duration(10) )

result = CompositeVideoClip([video, txt_clip]) # Overlay text on video
result.write_videofile("myHolidays_edited.webm",fps=25) # Many options...

这样的实例代码，一看就明白如何去用了。

您的代码没有提供示例，看的我一头雾水。。。。真是有种手中有个好宝贝，却不知道如何使用的赶脚。。（我是初学，让您见笑了。。）

**Comment by cherryoyo** [comment]
> > exe执行还是有些不太方便的。 首先，文件比较多。 另外，我也想把它放到python中，通过运行py文件的方式运行，这样也更加灵活。
> 
> 改下, main.py文件就行了

谢谢，我研究一下。

**Comment by YaoFANGUK** [comment]
```python
from backend.main import SubtitleExtractor
# 输入视频路径
# 新建字幕提取对象
se = SubtitleExtractor(video_path, subtitle_area)
# 开始提取字幕
se.run()
```

**Comment by cherryoyo** [comment]
> ```python
> from backend.main import SubtitleExtractor
> # 输入视频路径
> # 新建字幕提取对象
> se = SubtitleExtractor(video_path, subtitle_area)
> # 开始提取字幕
> se.run()
> ```

谢谢🙏

**Comment by Leonhardt92** [comment]
> ```python
> from backend.main import SubtitleExtractor
> # 输入视频路径
> # 新建字幕提取对象
> se = SubtitleExtractor(video_path, subtitle_area)
> # 开始提取字幕
> se.run()
> ```

你这个是默认字幕区域啊

**Comment by cherryoyo** [comment]
> 

`from backend.main import SubtitleExtractor
# 输入视频路径
# 新建字幕提取对象
video_path = '/Users/hiyoyo/Downloads/test02.mp4'
subtitle_area = 500,1300,0,1080
se = SubtitleExtractor(video_path, subtitle_area)
# 开始提取字幕
se.run()`

需要指定subtitle_area坐标的，只是这几个坐标我目前还找不准，不是多了就是少了，毕竟不是可视化的，不过总算是可以运行了。
