### ISSUE TITLE
连续使用一个月后的发现的问题与建议

### ISSUE THREAD

**Issue by royzengyi** [YaoFANGUK/video-subtitle-extractor#71]
已连续使用GUI版本一个月，感谢作者的开发及分享。
这里也反馈一下发现的问题及建议。

一.  时间轴准确度问题
1. 部分字幕起始时间不准确：大概8%的字幕会延迟2秒左右
2. 部分字幕的持续时间不准备：也大概8%的字幕要么持续时间过短要么过长

二. 字幕重复问题
同一句话，可能会生产多条，甚至十几条字幕，每条字幕可能有一个字不一样，我猜是机器学习拿不准把所有可能都输出了？

三. 字幕区域问题
现在选择视频后，默认画面显示第一帧，不能播放到有字幕的位置，但第一帧基本都不会有字幕。只能凭感觉，如果设置大了担心拖慢识别的速度，设置小了会漏掉字幕。每次都是把视频用其他播放器打开，调整窗口到相同大小来判断，但还是出现判断失误的情况。建议能支持播放到有字幕的帧再进行区域设置

现在提取字幕后，因为前两个问题，需要逐条字幕去确认时间轴和内容（因为不知道哪条不准），一部两小时左右影片基本需要半天时间来校对。不知道在算法上还有没有改进的空间。

**Comment by YaoFANGUK** [comment]
谢谢你的建议，有时间我会解决这些问题的
