### ISSUE TITLE
window_cpu版本提取字幕文件完成后不能重新打开新的视频文件

### ISSUE THREAD

**Issue by Leonhardt92** [YaoFANGUK/video-subtitle-extractor#72]
提取字幕文件完成后不能重新打开新的视频文件, 只能重启启动应用

**Comment by Narakuku** [comment]
GPU, same problem here!

```
字幕文件生成位置： //MySynology/Downloads/Temp/桥/桥.Bron.2013.S02.1080p.WEB-DL.H264.AAC-LeagueWEB/Bron.2013.S02E02.1080p.WEB-DL.H264.AAC-LeagueWEB.srt
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\resources\backend\main.py", line 173, in run
    reformat(os.path.join(os.path.splitext(self.video_path)[0] + '.srt'))
  File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\resources\backend\tools\reformat_en.py", line 29, in reformat
    typo_map = json.load(load_f)
  File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 83: character maps to <undefined>
```

**Comment by YaoFANGUK** [comment]
> GPU, same problem here!
> 
> ```
> 字幕文件生成位置： //MySynology/Downloads/Temp/桥/桥.Bron.2013.S02.1080p.WEB-DL.H264.AAC-LeagueWEB/Bron.2013.S02E02.1080p.WEB-DL.H264.AAC-LeagueWEB.srt
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\resources\backend\main.py", line 173, in run
>     reformat(os.path.join(os.path.splitext(self.video_path)[0] + '.srt'))
>   File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\resources\backend\tools\reformat_en.py", line 29, in reformat
>     typo_map = json.load(load_f)
>   File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\json\__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "C:\Users\lesjia\Desktop\vse_windows_GPU\vse\Python\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 83: character maps to <undefined>
> ```

不要直接生成字幕在群晖….估计编码错误

**Comment by YaoFANGUK** [comment]
> 提取字幕文件完成后不能重新打开新的视频文件, 只能重启启动应用

这个问题已经修复
