### ISSUE TITLE
请指定字幕区域 (ymin ymax xmin xmax)

### ISSUE THREAD

**Issue by Vicente5567** [YaoFANGUK/video-subtitle-extractor#81]
I'm on a Mac, running the CLI version.

Once I execute **python ./backend/main.py** and paste the video file into the terminal, I get this message: 请指定字幕区域 (ymin ymax xmin xmax)

What exactly am I supposed to write? Any specific commands? 

Thank you

**Comment by YaoFANGUK** [comment]
run ```gui.py``` and adjust subtitle area then click ```run```, we will see subtitle area in the output

<img src="https://s3.bmp.ovh/imgs/2022/01/5b1d31632cbb3a3c.png">

**Comment by Vicente5567** [comment]
Thank you, it did work.
