### ISSUE TITLE
每个视频都要重开一次软件吗

### ISSUE THREAD

**Issue by 2fdvr** [YaoFANGUK/video-subtitle-extractor#83]
Windows GPU版本
成功提取生成字幕文件以后各个按钮一直灰的无法点击，想要继续提取其他视频只能关掉重开软件，bug？

**Comment by freechaim** [comment]
是的，这个非常不方便，每次提取完后，需要关闭软件再次打开才能继续使用。

建议增加批量提取功能，感谢。

**Comment by YaoFANGUK** [comment]
现在不用了，使用最新的程序
