### ISSUE TITLE
GPU最低要求？

### ISSUE THREAD

**Issue by BrushXue** [YaoFANGUK/video-subtitle-extractor#86]
苹果用户，CPU提取太慢了，没有台式机显卡，只有一台960M的Windows笔记本
程序闪退，日志为空，研究了好久，最后通过手机Slow motion拍到CUDA error 98，查了一下是显卡太旧的意思。
能否在README里面强调一下显卡的最低要求？避免浪费大家的时间。

**Comment by eritpchy** [comment]
据说要6G显存以上才能玩爽这个
