### ISSUE TITLE
a little bug about time

### ISSUE THREAD

**Issue by awmmmm** [YaoFANGUK/video-subtitle-extractor#88]
thank u for your work!
![image](https://user-images.githubusercontent.com/89187860/159027618-1c0ebdf9-ebb5-4663-ae4b-e5660f833e2a.png)
i run the code with cli ,it extract subtitle accurately ,but it don,t show time I don,t know why,if u can explain why.thank u.look forward to your reply

**Comment by awmmmm** [comment]
![image](https://user-images.githubusercontent.com/89187860/159107724-3419031b-8026-4476-9883-b42ef27727f9.png)
but it seems cool when i extract another file.

**Comment by YaoFANGUK** [comment]
只有个别视频会出现这个问题对吧，你把视频发我看下

**Comment by YaoFANGUK** [comment]
已经修复
