### ISSUE TITLE
关于环境

### ISSUE THREAD

**Issue by maomao1025** [YaoFANGUK/video-subtitle-extractor#9]
作者您好，近期下载了你的代码之后在windows，cpu上运行很好，但是速度很慢，因此尝试在ubuntu18.04上运行您的代码，cuda版本为11.2，cudnn版本为8.2.0，飞浆版本为2.0.1，运行之后报错
![image](https://user-images.githubusercontent.com/39375578/119103800-27a0d800-ba4e-11eb-91c3-7a05d18a7df2.png)
请问这是什么原因呢？
gpu如图所示：
![image](https://user-images.githubusercontent.com/39375578/119103921-443d1000-ba4e-11eb-9a7c-326ed4968a0f.png)

**Comment by YaoFANGUK** [comment]
你nvcc -V截个图我看看

**Comment by maomao1025** [comment]
![Uploading image.png…]()

**Comment by maomao1025** [comment]
![image](https://user-images.githubusercontent.com/39375578/119106442-f1b12300-ba50-11eb-8f2b-111df1053d83.png)

**Comment by YaoFANGUK** [comment]
你的cuda版本是10.2的 通过nvidia-smi命令打印出来的cuda信息指的是这个驱动最高支持的cuda版本是11.2，出现Segmentation fault的情况通常可能是paddle版本和cuda、cudnn环境不匹配导致的。

**Comment by maomao1025** [comment]
你好，已经解决了，cudnn版本由8.2.0降到7.6.5版本之后可以正常运行了，谢谢
