### ISSUE TITLE
srt字幕時間出現 00:00:00,000 

### ISSUE THREAD

**Issue by hongyuntw** [YaoFANGUK/video-subtitle-extractor#94]
您好
我在使用backend/main.py時
辨識影片常常會在srt檔裡面發現以下資料
辨識影片 : https://www.youtube.com/watch?v=E2fGIaUN8to&ab_channel=Listentome
```
74
00:03:59,973 --> 00:00:00,000
在欠发达地区 还是没有普及的

82
00:00:00,000 --> 00:04:29,403
它就像恶魔的谊咒一般

88
00:00:00,000 --> 00:04:50,123
流感病毒能够跨物种传播

93
00:00:00,000 --> 00:05:08,441
作为未来科学家的使命感
````
如上述所示，會有滿多字幕起始時間或開始時間是 00:00:00,000

想請問有可能會是甚麼問題，我跑滿多部影片都會出現這個問題

**Comment by YaoFANGUK** [comment]
应该是个bug 你应该不是跑的windows吧

**Comment by hongyuntw** [comment]
> 应该是个bug 可能是视频帧转时间戳的时候不正确 你应该不是跑的windows吧， 可以加QQ群讨论一下吗，我的政府不允许我访问youtube

作者您好，謝謝你的回覆
我已經解決了這個問題
我是在windows系統上跑的，這個問題好像是因為我把自動檢測出來的場景問字區域全部刪除掉了
我把那個function註解掉或是給定字幕區域就沒有這個問題，可能跟那個function有關！
謝謝
